def problem045():
    """


    Triangle, pentagonal, and hexagonal numbers are generated by the following
       formulae:

       Triangle     T[n]=n(n+1)/2    1, 3, 6, 10, 15, ...
       Pentagonal   P[n]=n(3n−1)/2   1, 5, 12, 22, 35, ...
       Hexagonal    H[n]=n(2n−1)     1, 6, 15, 28, 45, ...

       It can be verified that T[285] = P[165] = H[143] = 40755.

       Find the next triangle number that is also pentagonal and hexagonal.
    """
    i = 286
    j = 166
    k = 144
    while True:
        triangle = i * (i + 1) // 2
        pentagon = j * (j * 3 - 1) // 2
        hexagon = k * (k * 2 - 1)
        minimum = min(triangle, pentagon, hexagon)
        if minimum == max(triangle, pentagon, hexagon):
            return triangle
        if minimum == triangle:
            i += 1
        if minimum == pentagon:
            j += 1
        if minimum == hexagon:
            k += 1


if __name__ == "__main__":
    print(problem045())
